export enum LocationType {
  Deck = 1,
  AscensionDeck = 2,
  Discard = 3,
  PlayerHand = 10,
  DraftArea = 11,
  ConstructionArea = 12,
  ConstructionCardCost = 13,
  ConstructedDevelopments = 14,
  AvailableResources = 15,
  EmpireCardResources = 16,
  EmpireCardSpace = 17,
  KrystalliumStock = 18,
  CharacterStock = 20,
  PlayerCharacters = 21,
  DevelopmentCardProduction = 22,
  DevelopmentCardCostSpace = 23,
  DevelopmentCardRecyclingBonus = 24,
  DevelopmentCardVictoryPoints = 25
}
