enum DragObjectType {
  DEVELOPMENT_FROM_HAND = 'DEVELOPMENT_FROM_HAND',
  DEVELOPMENT_FROM_DRAFT_AREA = 'DEVELOPMENT_FROM_DRAFT_AREA',
  RESOURCE = 'RESOURCE',
  KRYSTALLIUM_FROM_EMPIRE = 'KRYSTALLIUM_FROM_EMPIRE'
}

export default DragObjectType